// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {BrevisAppZkOnly} from "./lib/BrevisAppZkOnly.sol";
import {IStandingRegistry} from "./interfaces/IStandingRegistry.sol";

/// @title TenureRegistry
/// @notice Records proven directional balance from a Brevis ZK callback, and answers the one
///         question the hook asks: how much standing does this address have?
///
/// @dev THE SECURITY-CRITICAL LINE IS `_vkHash != expectedVkHash`. `brevisCallback` hands us
///      whatever verifying-key hash the proof was made under. If we do not check it, anyone can
///      submit a proof generated by a *different circuit* — one that outputs whatever they like —
///      and drive this callback. There is a published audit finding against exactly this pattern.
///      `expectedVkHash` therefore starts unset and every callback reverts until an operator sets
///      it; an unset registry accepts nothing rather than accepting everything.
///
/// @dev STANDING IS UNDEFINED BELOW A MINIMUM SAMPLE. Directional balance over a handful of swaps
///      is noise, not a measurement: at four swaps a single extra trade moves it 5,000 bps. Rather
///      than pick a lookback window that flatters the numbers, an address below
///      `MIN_STANDING_SWAPS` simply has no standing and falls to base depth. That is a threshold on
///      evidence sufficiency, not on the metric — it separates "measured" from "not yet measured",
///      never good traders from bad. Derivation in analysis/minimum-sample-decision.md, recorded
///      before any numbers were run at any N.
///
/// @dev NO FEE LOGIC EXISTS HERE AND NONE MAY BE ADDED (the fee-parity rule).
contract TenureRegistry is BrevisAppZkOnly, IStandingRegistry {
    /// @notice Minimum observed swaps before an address has standing at all.
    /// @dev N = 20, chosen so one additional swap cannot move balance by more than 500 bps:
    ///      10000/(N+1) <= 500  =>  N >= 19. Also fits the circuit's 32-receipt budget.
    uint256 public constant MIN_STANDING_SWAPS = 20;

    /// @notice Full basis-point scale. A perfectly two-sided history scores this.
    uint256 public constant BPS = 10_000;

    /// @notice What the circuit proved about one address.
    struct Standing {
        uint16 balanceBps; // directional balance, 0 = one-sided, 10000 = perfectly two-sided
        uint16 swapCount; // swaps the proof actually observed
        uint64 fromBlock; // attested window start
        uint64 toBlock; // attested window end
        uint64 recordedAt; // when the callback landed
    }

    mapping(address => Standing) public standing;

    /// @notice The verifying-key hash of the circuit we accept proofs from.
    bytes32 public expectedVkHash;

    address public operator;

    error NotOperator();
    error UnexpectedVkHash(bytes32 got, bytes32 expected);
    error VkHashNotSet();
    error MalformedCircuitOutput(uint256 length);

    event VkHashUpdated(bytes32 vkHash);
    event StandingRecorded(
        address indexed trader, uint16 balanceBps, uint16 swapCount, uint64 fromBlock, uint64 toBlock
    );

    modifier onlyOperator() {
        if (msg.sender != operator) revert NotOperator();
        _;
    }

    constructor(address _brevisRequest, address _operator) BrevisAppZkOnly(_brevisRequest) {
        operator = _operator;
    }

    /// @notice Set the verifying-key hash this registry will accept proofs under.
    /// @dev Until this is called, every callback reverts with `VkHashNotSet`. Verify by reading
    ///      `expectedVkHash()` back from the deployed contract — not from a deploy log.
    /// @param vkHash The circuit's vk hash, as printed by the prover at setup.
    function setVkHash(bytes32 vkHash) external onlyOperator {
        expectedVkHash = vkHash;
        emit VkHashUpdated(vkHash);
    }

    /// @notice Brevis callback. Records standing if, and only if, the proof came from our circuit.
    /// @param _vkHash The verifying-key hash the proof was generated under.
    /// @param _appCircuitOutput ABI-packed circuit output.
    function handleProofResult(bytes32 _vkHash, bytes calldata _appCircuitOutput) internal override {
        // Fail closed on an unconfigured registry rather than accepting an arbitrary circuit.
        if (expectedVkHash == bytes32(0)) revert VkHashNotSet();
        if (_vkHash != expectedVkHash) revert UnexpectedVkHash(_vkHash, expectedVkHash);

        (address trader, uint16 balanceBps, uint16 swapCount, uint64 fromBlock, uint64 toBlock) =
            decodeOutput(_appCircuitOutput);

        standing[trader] = Standing({
            balanceBps: balanceBps,
            swapCount: swapCount,
            fromBlock: fromBlock,
            toBlock: toBlock,
            recordedAt: uint64(block.timestamp)
        });

        emit StandingRecorded(trader, balanceBps, swapCount, fromBlock, toBlock);
    }

    /// @notice Decode the circuit's packed output.
    /// @dev Layout is fixed by DirectionalBalanceCircuit.Define:
    ///      address(20) ‖ balanceBps(2) ‖ swapCount(2) ‖ fromBlock(8) ‖ toBlock(8) = 40 bytes.
    /// @param o The packed output.
    function decodeOutput(bytes calldata o)
        public
        pure
        returns (address trader, uint16 balanceBps, uint16 swapCount, uint64 fromBlock, uint64 toBlock)
    {
        if (o.length < 40) revert MalformedCircuitOutput(o.length);
        trader = address(bytes20(o[0:20]));
        balanceBps = uint16(bytes2(o[20:22]));
        swapCount = uint16(bytes2(o[22:24]));
        fromBlock = uint64(bytes8(o[24:32]));
        toBlock = uint64(bytes8(o[32:40]));
    }

    /// @inheritdoc IStandingRegistry
    /// @dev Returns 0 below the minimum sample. An address with too little history does not score
    ///      badly — it is simply not yet measured, and receives base depth like anyone else.
    function standingOf(address trader) external view returns (uint256) {
        Standing memory s = standing[trader];
        if (s.swapCount < MIN_STANDING_SWAPS) return 0;
        return s.balanceBps;
    }
}
